/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113151-g238f9de-Reino"
#endif /* AVUTIL_FFVERSION_H */
