name: Windows CMake

on:
  push:
  pull_request:

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        arch:
          - name: x86
            prefix: i686-w64-mingw32
          - name: x86_64
            prefix: x86_64-w64-mingw32

    runs-on: ubuntu-latest
    env:
      PREFIX: ${{ matrix.arch.prefix }}
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Install dependencies
        run: |
          sudo apt update
          [ "${{ matrix.arch.name }}" = "x86" ] && PKGSUFFIX="i686" || PKGSUFFIX="x86-64"
          sudo apt install -y gcc-mingw-w64-$PKGSUFFIX binutils-mingw-w64-$PKGSUFFIX ninja-build

      - name: Configure vcpkg
        uses: lukka/run-vcpkg@v11.6
        with:
          vcpkgJsonGlob: "**/vcpkg.json"

      - name: Configure CMake
        run: |
          [ "${{ matrix.arch.name }}" = "x86" ] && ARCH="x86" || ARCH="x64"
          cmake -B build.cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=$ARCH-windows-static

      - name: Build SRB2
        run: |
          cmake --build build.cmake --parallel 1 -- --keep-going

      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: srb2banpyura-windows-cmake-${{ matrix.arch.name }}-${{ github.sha }}
          path: |
            bin/
