name: Windows CMake

on:
  push:
  pull_request:

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        arch:
          - name: x86
            prefix: i686-w64-mingw32
          - name: x86_64
            prefix: x86_64-w64-mingw32

    runs-on: ubuntu-latest
    env:
      VCPKG_TARGET_TRIPLET: x86-mingw-static

    steps:
      - uses: actions/checkout@v6.0.1

      - name: Install dependencies
        run: |
          sudo apt update
          [ "${{ matrix.arch.name }}" = "x86" ] && PKGSUFFIX="i686" || PKGSUFFIX="x86-64"
          sudo apt install -y g++-mingw-w64-$PKGSUFFIX-posix binutils-mingw-w64-$PKGSUFFIX ninja-build

      - name: Configure vcpkg
        uses: lukka/run-vcpkg@v11.6
        with:
          runVcpkgInstall: true
        env:
          VCPKG_BINARY_SOURCES: default,readwrite

      - name: Configure vcpkg cache
        uses: actions/cache@v6.1.0
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ runner.os }}-${{ matrix.arch.name }}-vcpkg-binary-cache-${{ hashFiles('vcpkg*.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch.name }}-vcpkg-binary-cache-

      - name: Configure CMake
        run: |
          [ "${{ matrix.arch.name }}" = "x86" ] && ARCH="x86" || ARCH="x64"
          cmake -B build.cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=$ARCH-mingw-static -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/toolchains/mingw.cmake 

      - name: Build SRB2
        run: |
          cmake --build build.cmake --parallel 1 -- --keep-going

      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: srb2banpyura-windows-cmake-${{ matrix.arch.name }}-${{ github.sha }}
          path: |
            bin/
