name: Windows CMake

on:
  push:
  pull_request:

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        arch:
          - name: x86
            prefix: i686-w64-mingw32
          - name: x86_64
            prefix: x86_64-w64-mingw32

    runs-on: ubuntu-latest
    env:
      VCPKG_TARGET_TRIPLET: x86-mingw-static

    steps:
      - uses: actions/checkout@v6.0.1

      - name: Install dependencies
        run: |
          sudo apt update
          [ "${{ matrix.arch.name }}" = "x86" ] && PKGSUFFIX="i686" || PKGSUFFIX="x86-64"
          sudo apt install -y g++-mingw-w64-$PKGSUFFIX-posix binutils-mingw-w64-$PKGSUFFIX ninja-build

      - name: Configure vcpkg
        uses: lukka/run-vcpkg@v11.6
        with:
          vcpkgDirectory: "${{ github.workspace }}/vcpkgslop"

      - name: Configure vcpkg cache
        uses: actions/cache@v6.1.0
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ runner.os }}-${{ matrix.arch.name }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch.name }}-vcpkg-

      - name: Configure CMake
        run: |
          [ "${{ matrix.arch.name }}" = "x86" ] && ARCH="x86" || ARCH="x64"
          PREFIX="${{ matrix.arch.prefix }}"
          
          export CC="$PREFIX-gcc"
          export CXX="$PREFIX-g++"
          export LD="$PREFIX-ld"
          
          export VCPKG_BINARY_SOURCES="clear;files,$VCPKG_DEFAULT_BINARY_CACHE,readwrite"
          export VCPKG_DEFAULT_BINARY_CACHE="${{ github.workspace }}/build/vcpkg-binary-cache"
          mkdir -p "$VCPKG_DEFAULT_BINARY_CACHE"
          
          cmake -B build.cmake -G "Unix Makefiles" \
            -DSRB2_CONFIG_USE_GME=ON \
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkgslop/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET="$ARCH-mingw-static" \
            -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkgslop/scripts/toolchains/mingw.cmake"

      - name: Build SRB2
        run: |
          cmake --build build.cmake --parallel 1 -- --keep-going

      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: srb2banpyura-windows-cmake-${{ matrix.arch.name }}-${{ github.sha }}
          path: |
            build.cmake/bin/
